# .github/workflows/monitor.yml
name: Monitor Dockerfile Change

on:
  schedule:
    - cron: '0 2 * * *' # 每天 UTC 2 点（北京时间 10 点）
  workflow_dispatch: # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Get latest commit of Dockerfile
        id: get_commit
        run: |
          curl -s 'https://api.github.com/repos/base/node/commits?path=geth/Dockerfile&per_page=1' > latest.json
          sha=$(jq -r '.[0].sha' latest.json)
          echo "Latest SHA: $sha"
          echo "::set-output name=sha::$sha"

      - name: Load previous SHA
        id: read_prev
        run: |
          if [ -f prev_sha.txt ]; then
            echo "Previous SHA: $(cat prev_sha.txt)"
          else
            echo "no previous sha"
          fi

      - name: Compare and send email if changed
        if: steps.get_commit.outputs.sha != steps.read_prev.outputs.sha
        run: |
          echo "SHA changed, sending email"
          echo "${{ steps.get_commit.outputs.sha }}" > prev_sha.txt

      - name: Commit new SHA
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update stored SHA"
          file_pattern: prev_sha.txt

      - name: Send Email
        if: steps.get_commit.outputs.sha != steps.read_prev.outputs.sha
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Dockerfile updated!"
          to: fangtaoma@gmail.com
          from: Dockerfile Monitor <fangtaoma@gmail.com>
          body: |
            The file https://github.com/base/node/blob/main/geth/Dockerfile has changed.
            Latest SHA: ${{ steps.get_commit.outputs.sha }}
